# Generated by Django 2.1.1 on 2018-12-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='contact',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
