# Generated by Django 2.1.1 on 2018-12-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_auto_20181213_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_score', models.IntegerField(blank=True)),
                ('away_score', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='score',
        ),
        migrations.AddField(
            model_name='matchstat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.Match'),
        ),
    ]
