# Generated by Django 2.1.1 on 2018-12-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_auto_20181213_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='broadcast_msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_time', models.TimeField()),
                ('message', models.CharField(max_length=40)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='football.Match')),
            ],
        ),
    ]
