# Generated by Django 2.1.1 on 2018-12-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20181226_0945'),
        ('football', '0004_broadcast_msg'),
    ]

    operations = [
    ]
