# Generated by Django 2.1.4 on 2019-01-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_auto_20181226_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='contact',
            new_name='jersey_color',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='team_name',
        ),
        migrations.AddField(
            model_name='team',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='team',
            name='player_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='team',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
