# Generated by Django 2.1.4 on 2019-01-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20190102_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='document',
            new_name='jersey_image',
        ),
    ]
