# Generated by Django 2.1.1 on 2018-12-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_merge_20181227_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broadcast_msg',
            old_name='match_id',
            new_name='match',
        ),
        migrations.AlterField(
            model_name='match',
            name='starttime1',
            field=models.TimeField(default='00:00:00', help_text="Format:'HH:MM:SS'"),
        ),
    ]
