# Generated by Django 2.1.1 on 2018-12-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_auto_20181228_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast_msg',
            name='happened_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='broadcast_msg',
            name='message',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
