# Generated by Django 2.1.1 on 2019-01-02 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_auto_20190102_1908'),
        ('football', '0008_auto_20181228_0155'),
    ]

    operations = [
    ]
