# Generated by Django 2.1.1 on 2019-01-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_merge_20190102_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast_msg',
            name='happened_time',
            field=models.TimeField(default='00:00', help_text="Format:'MM:SS'"),
        ),
    ]
