# Generated by Django 2.1.1 on 2019-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_auto_20190102_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='player_number',
            field=models.IntegerField(default=0),
        ),
    ]
