# Generated by Django 2.1.4 on 2019-01-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_auto_20190103_1639'),
        ('football', '0007_auto_20190103_1953'),
    ]

    operations = [
    ]
