# Generated by Django 2.1.4 on 2019-01-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_merge_20190104_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast_msg',
            name='happened_time',
            field=models.CharField(default='00:00', help_text="Format:'MM:SS'", max_length=20),
        ),
    ]
