# Generated by Django 2.1.2 on 2018-12-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='from_email',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='contactform',
            name='message',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='contactform',
            name='subject',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
