# Generated by Django 2.1.4 on 2018-12-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create_The_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=50)),
                ('default_pos', models.CharField(max_length=50)),
                ('pos', models.CharField(blank=True, max_length=100)),
                ('Host_Name', models.CharField(max_length=100)),
                ('Host_ID', models.CharField(max_length=20)),
                ('Host_Phone_Number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=10)),
            ],
        ),
    ]
