# Generated by Django 2.1.4 on 2018-12-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Create_The_Game',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
